/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--color-primary-50))',
          100: 'rgb(var(--color-primary-100))',
          200: 'rgb(var(--color-primary-200))',
          300: 'rgb(var(--color-primary-300))',
          400: 'rgb(var(--color-primary-400))',
          500: 'rgb(var(--color-primary-500))',
          600: 'rgb(var(--color-primary-600))',
          700: 'rgb(var(--color-primary-700))',
          800: 'rgb(var(--color-primary-800))',
          900: 'rgb(var(--color-primary-900))',
        },
        secondary: {
          50: 'rgb(var(--color-secondary-50))',
          100: 'rgb(var(--color-secondary-100))',
          200: 'rgb(var(--color-secondary-200))',
          300: 'rgb(var(--color-secondary-300))',
          400: 'rgb(var(--color-secondary-400))',
          500: 'rgb(var(--color-secondary-500))',
          600: 'rgb(var(--color-secondary-600))',
          700: 'rgb(var(--color-secondary-700))',
          800: 'rgb(var(--color-secondary-800))',
          900: 'rgb(var(--color-secondary-900))',
        },
        success: {
          50: 'rgb(var(--color-success-50))',
          100: 'rgb(var(--color-success-100))',
          200: 'rgb(var(--color-success-200))',
          300: 'rgb(var(--color-success-300))',
          400: 'rgb(var(--color-success-400))',
          500: 'rgb(var(--color-success-500))',
          600: 'rgb(var(--color-success-600))',
          700: 'rgb(var(--color-success-700))',
          800: 'rgb(var(--color-success-800))',
          900: 'rgb(var(--color-success-900))',
        },
        error: {
          50: 'rgb(var(--color-error-50))',
          100: 'rgb(var(--color-error-100))',
          200: 'rgb(var(--color-error-200))',
          300: 'rgb(var(--color-error-300))',
          400: 'rgb(var(--color-error-400))',
          500: 'rgb(var(--color-error-500))',
          600: 'rgb(var(--color-error-600))',
          700: 'rgb(var(--color-error-700))',
          800: 'rgb(var(--color-error-800))',
          900: 'rgb(var(--color-error-900))',
        },
        warning: {
          50: 'rgb(var(--color-warning-50))',
          100: 'rgb(var(--color-warning-100))',
          200: 'rgb(var(--color-warning-200))',
          300: 'rgb(var(--color-warning-300))',
          400: 'rgb(var(--color-warning-400))',
          500: 'rgb(var(--color-warning-500))',
          600: 'rgb(var(--color-warning-600))',
          700: 'rgb(var(--color-warning-700))',
          800: 'rgb(var(--color-warning-800))',
          900: 'rgb(var(--color-warning-900))',
        },
        info: {
          50: 'rgb(var(--color-info-50))',
          100: 'rgb(var(--color-info-100))',
          200: 'rgb(var(--color-info-200))',
          300: 'rgb(var(--color-info-300))',
          400: 'rgb(var(--color-info-400))',
          500: 'rgb(var(--color-info-500))',
          600: 'rgb(var(--color-info-600))',
          700: 'rgb(var(--color-info-700))',
          800: 'rgb(var(--color-info-800))',
          900: 'rgb(var(--color-info-900))',
        },
        gray: {
          50: 'rgb(var(--color-gray-50))',
          100: 'rgb(var(--color-gray-100))',
          200: 'rgb(var(--color-gray-200))',
          300: 'rgb(var(--color-gray-300))',
          400: 'rgb(var(--color-gray-400))',
          500: 'rgb(var(--color-gray-500))',
          600: 'rgb(var(--color-gray-600))',
          700: 'rgb(var(--color-gray-700))',
          800: 'rgb(var(--color-gray-800))',
          900: 'rgb(var(--color-gray-900))',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        serif: ['var(--font-serif)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'base': 'var(--font-size-base)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        '6xl': 'var(--font-size-6xl)',
        '7xl': 'var(--font-size-7xl)',
        '8xl': 'var(--font-size-8xl)',
        '9xl': 'var(--font-size-9xl)',
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        extralight: 'var(--font-weight-extralight)',
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
        black: 'var(--font-weight-black)',
      },
      lineHeight: {
        none: 'var(--line-height-none)',
        tight: 'var(--line-height-tight)',
        snug: 'var(--line-height-snug)',
        normal: 'var(--line-height-normal)',
        relaxed: 'var(--line-height-relaxed)',
        loose: 'var(--line-height-loose)',
      },
      letterSpacing: {
        tighter: 'var(--letter-spacing-tighter)',
        tight: 'var(--letter-spacing-tight)',
        normal: 'var(--letter-spacing-normal)',
        wide: 'var(--letter-spacing-wide)',
        wider: 'var(--letter-spacing-wider)',
        widest: 'var(--letter-spacing-widest)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inner': 'var(--shadow-inner)',
        'none': 'var(--shadow-none)',
      },
      zIndex: {
        '0': 'var(--z-0)',
        '10': 'var(--z-10)',
        '20': 'var(--z-20)',
        '30': 'var(--z-30)',
        '40': 'var(--z-40)',
        '50': 'var(--z-50)',
        'auto': 'var(--z-auto)',
      },
      transitionProperty: {
        'none': 'var(--transition-property-none)',
        'all': 'var(--transition-property-all)',
        'colors': 'var(--transition-property-colors)',
        'opacity': 'var(--transition-property-opacity)',
        'shadow': 'var(--transition-property-shadow)',
        'transform': 'var(--transition-property-transform)',
      },
      transitionDuration: {
        '75': 'var(--transition-duration-75)',
        '100': 'var(--transition-duration-100)',
        '150': 'var(--transition-duration-150)',
        '200': 'var(--transition-duration-200)',
        '300': 'var(--transition-duration-300)',
        '500': 'var(--transition-duration-500)',
        '700': 'var(--transition-duration-700)',
        '1000': 'var(--transition-duration-1000)',
      },
      transitionTimingFunction: {
        'linear': 'var(--transition-timing-linear)',
        'in': 'var(--transition-timing-in)',
        'out': 'var(--transition-timing-out)',
        'in-out': 'var(--transition-timing-in-out)',
      },
      screens: {
        'xs': 'var(--screen-xs)',
        'sm': 'var(--screen-sm)',
        'md': 'var(--screen-md)',
        'lg': 'var(--screen-lg)',
        'xl': 'var(--screen-xl)',
        '2xl': 'var(--screen-2xl)',
      },
      container: {
        center: true,
        padding: '1rem',
        screens: {
          'sm': 'var(--container-sm)',
          'md': 'var(--container-md)',
          'lg': 'var(--container-lg)',
          'xl': 'var(--container-xl)',
          '2xl': 'var(--container-2xl)',
        },
      },
      gridTemplateColumns: {
        '1': 'repeat(var(--grid-cols-1), minmax(0, 1fr))',
        '2': 'repeat(var(--grid-cols-2), minmax(0, 1fr))',
        '3': 'repeat(var(--grid-cols-3), minmax(0, 1fr))',
        '4': 'repeat(var(--grid-cols-4), minmax(0, 1fr))',
        '5': 'repeat(var(--grid-cols-5), minmax(0, 1fr))',
        '6': 'repeat(var(--grid-cols-6), minmax(0, 1fr))',
        '7': 'repeat(var(--grid-cols-7), minmax(0, 1fr))',
        '8': 'repeat(var(--grid-cols-8), minmax(0, 1fr))',
        '9': 'repeat(var(--grid-cols-9), minmax(0, 1fr))',
        '10': 'repeat(var(--grid-cols-10), minmax(0, 1fr))',
        '11': 'repeat(var(--grid-cols-11), minmax(0, 1fr))',
        '12': 'repeat(var(--grid-cols-12), minmax(0, 1fr))',
        'none': 'var(--grid-cols-none)',
      },
      animation: {
        'none': 'var(--animation-none)',
        'spin': 'var(--animation-spin)',
        'ping': 'var(--animation-ping)',
        'pulse': 'var(--animation-pulse)',
        'bounce': 'var(--animation-bounce)',
      },
      opacity: {
        '0': 'var(--opacity-0)',
        '5': 'var(--opacity-5)',
        '10': 'var(--opacity-10)',
        '20': 'var(--opacity-20)',
        '25': 'var(--opacity-25)',
        '30': 'var(--opacity-30)',
        '40': 'var(--opacity-40)',
        '50': 'var(--opacity-50)',
        '60': 'var(--opacity-60)',
        '70': 'var(--opacity-70)',
        '75': 'var(--opacity-75)',
        '80': 'var(--opacity-80)',
        '90': 'var(--opacity-90)',
        '95': 'var(--opacity-95)',
        '100': 'var(--opacity-100)',
      },
      // Custom component specific extensions
      height: {
        'memory-bank-card': 'var(--memory-bank-card-height)',
        'memory-bank-search': 'var(--memory-bank-search-height)',
        'workflow-node': 'var(--workflow-node-height)',
        'dashboard-chart': 'var(--dashboard-chart-height)',
        'dashboard-stat-card': 'var(--dashboard-stat-card-height)',
        'auth-input': 'var(--auth-input-height)',
      },
      width: {
        'workflow-node': 'var(--workflow-node-width)',
        'auth-form': 'var(--auth-form-width)',
      },
      borderWidth: {
        'workflow-edge': 'var(--workflow-edge-width)',
      },
    },
  },
  plugins: [],
}
